---
title: Rotherham MBC Design Manual
timezone: Europe/London
description: Design System

# URL settings
baseurl: "/design/"
url: "https://rothgov.github.io"

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
